# Generated by Django 4.0.2 on 2022-03-20 19:25

from django.db import migrations

""" 
Logic da copy_src_to_dst
SRC = Source (can be a Abstrct logic or a Multi Table Inheritance)
DST = Destination (can be a Abstrct logic or a Multi Table Inheritance)
For SRC, intance a DST with all attributes
Save the DST
Associate the speakers object of SRC in DST
Delete the SRC
"""


def copy_src_to_dst(Source, Destination):
    for src in Source.objects.all():
        dst = Destination(
            title=src.title,
            start=src.start,
            description=src.description,
            slots=src.slots
        )

        dst.save()
        dst.speakers.set(src.speakers.all())
        src.delete()


def forward_course_abc_to_mti(apps, schema_editor):
    copy_src_to_dst(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )


def backward_course_abc_to_mti(apps, schema_editor):
    copy_src_to_dst(
        apps.get_model('core', 'CourseOld'),
        apps.get_model('core', 'Course')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_course'),
    ]

    operations = [
        migrations.RunPython(forward_course_abc_to_mti, backward_course_abc_to_mti)
    ]
